### ISSUE TITLE
Code Review on Math Lib

### ISSUE THREAD

**Issue by lzfcc** [lzfcc/Chinese-Ancient-Calendar#8]
https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/d4ba64aa820646e67df93b44e87b57c5b3970bdb/src/Cal/equa_math.mjs#L3

```js
export const isSame = (arr1, arr2) => {
    let flag = true
    if (arr1.length !== arr2.length) { // 这句还可以
        flag = false
    } else {
        arr1.forEach(item => {
            if (arr2.indexOf(item) === -1) { 
                flag = false
            }
        })
    }
    return flag // 所以，只要 arr1 的每个元素都在 arr2 中有出现过，他们就一样了？
}
```
随便验证一下就不对了啊，比如`arr1 = [1,1,2], arr2 = [1,2,2]`
看的什么垃圾博客啊，面试算法题要写成这样直接挂了好吗？而且，这样写法，是`O(n^2)`复杂度（因为相当于两层 for 循环）。

```js
export const isSame = (arr1, arr2) => {
    if (arr1.length !== arr2.length) {
        return false
    }
    arr1.sort((a, b) => a - b) // sort ascendingly
    arr2.sort((a, b) => a - b)
    for (let i = 0; i < arr1.length; i++) {
        if (arr1[i] !== arr2[i]) return false
    }
    return true
}
```
时间复杂度`2*O(nlog(n)) + O(n) = O(nlog(n))`，better。（竟然在试图教你学会写程序）

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/d4ba64aa820646e67df93b44e87b57c5b3970bdb/src/Cal/equa_math.mjs#L17

没看懂在算啥，正确性存疑。可以在函数定义前一行写注释，这样可以在 VSCode 中调用函数时展示出来。

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/d4ba64aa820646e67df93b44e87b57c5b3970bdb/src/Cal/equa_math.mjs#L38

正确性大概没问题（一定范围内）。Int 数组应该装 int 型吧，toPrecision 是返回字符串，只有 Portion == 1 时才会 int。大量浮点运算，看着不太稳。另外对输入格式容错性太低，加几个空格就不行了。
```js
export const Deci2Int = str => { // 輸入字符串
    const Raw = str.split(/[^0-9.+-]/).filter(x => Boolean(x))
// 先按照所有非数字和小数点正负号的字符分开（结果会出现空字符串），再把空字符串过滤出去
    let prec = 0
    let Portion = 1
    const Int = []
    for (let i = 0; i < Raw.length; i++) {
        Int[i] = +Raw[i] // 这步是可能产生 NaN 的，后面考虑处理（比如 fallback 成 0）
        const dotIndex = Raw[i].indexOf('.') // -1 means not found
        if (dotIndex >= 0) {
            prec = Math.max(Raw[i].length - 1 - dotIndex, prec)   
        }
    }
    if (prec) {
        Portion = 10 ** prec
        for (let i = 0; i < Int.length; i++) {
            Int[i] *= Portion
        }
    }
    return { Int, Portion }
}
```

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/d4ba64aa820646e67df93b44e87b57c5b3970bdb/src/Cal/equa_math.mjs#L62

这个写的不错（为什么没有把这个思路用在上一个函数上？）！但是既然刚刚已经写过 Deci2Int，为什么要另起炉灶呢，毕竟，函数是用来复用的（当然，得首先保证正确）！

```js
const DeciFrac2Frac = Deci => { // 把有小數點的分數轉換為整數分數
    const { Int } = Deci2Int(Deci) // Portion 用不到
    return Int[0] + '/' + Int[1]
}
```

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/d4ba64aa820646e67df93b44e87b57c5b3970bdb/src/Cal/equa_math.mjs#L74

好么，经典面试题。写的好像没问题，但是返回值有点迷。返回一个 a，一个 cString 是什么鬼呢？不应该是 a 和 b 吗？至于合并在一起的 c，调用者自己去合就好了啊。代码好像有点繁琐，不过正确就好。输入可以加一个默认参数，不然一旦没传就直接不行了。

```js
export const SliceNum = (Input, num = 3) => {
    // ...
    return {a, b} // 这不仅仅是函数自己用的变量名，叫 { int, dec } 也许更友好一点呢
}
```

**Comment by kujihhoe** [comment]
commit info:
2021October25 at 14:49:22 GMT+8
8f73969b196d03b7b396462dfa62d9476bb4288d
