### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by lzfcc** [lzfcc/Chinese-Ancient-Calendar#9]
https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/6f29eacd34863fe3bbe257d2fee6dd7adf42889f/src/Cal/equa_sqrt.mjs#L6

有什么问题？需要描述一下。

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/6f29eacd34863fe3bbe257d2fee6dd7adf42889f/src/Cal/equa_geometry.mjs#L23

我理解是，由于前面的计算，`Temp1`, `Temp2`就是`Big`对象了，所以不必再用`big()`包裹。同理，`big(Temp2).div(2).pow(2)`的结果也是`Big`对象，同样不需要再用`big()`包裹。其他相似应用也可检查一下，如 equa_sn.mjs。

https://github.com/lzfcc/Chinese-Ancient-Calendar/blob/6f29eacd34863fe3bbe257d2fee6dd7adf42889f/src/Cal/equa_high.mjs#L9

看起来是要算`a_9 * x ^ 9 + a_8 * x ^ 8 + ... + a_0`，但是写得太傻了。
首先，考虑改用不定参数列表（必须作为最后一个参数）。
```js
export const HighEqua1 = (upperRaw, ...coefficients) => { // coefficient: 系数；...表示不定参数（数组）
    if (coefficients.length > 9) {
        // throw Error('不支持高于9次多项式') // if needed
        return '0'
    }
    let mid = 0
    let lower = 0
    let upper = Number(upperRaw)
    const equation = (x) => {
        // ...
    }
    // 这一段看起来是二分法？正确性待考察，先跳过
    if (big(upper).eq(upperRaw)) {
        throw (new Error('[高次方程] 無解，可能估根錯誤'))
    }
    return upper.toFixed(15) // 就一个返回值，不要用对象形式了！
}
```
有一个注意点是，尽可能多算加减，少算乘除，因为乘除的计算很昂贵。试比较：
`a_9 * x ^ 9 + a_8 * x ^ 8 + ... + a_0` 共 (10+9+...+1) = 55 次乘法，9 次加法。
但是如果变形成：
`(...((a_9 * x + a_8 ) * x + a_7) * x.... ) * x + a_0` 共 9 次乘法，9 次加法。当然这只是理论上，其实对于我们这规模的输入差别不大（甚至可能反优化）。

```js
    const equation = (x) => {
        let ans = big(0)
        for (let i = 0; i < coefficients.length; i++) {
            ans = ans.mul(x).add(big(coefficients[i])) 
        }
        return ans
    }
```

**Comment by kujihhoe** [comment]
2021October25 at 23:08:35 GMT+8
3f0dfa257999d9e0217ac603b4ab090f0a1984fc
